//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal help() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudPanel.localization.help", typeof(help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is delivered to a recipient in this organization.
        /// </summary>
        internal static string Domains_Autoritative {
            get {
                return ResourceManager.GetString("Domains_Autoritative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting this domain as the default makes sure this domain is the first selected in all fields that contain domains..
        /// </summary>
        internal static string Domains_DefaultDomain {
            get {
                return ResourceManager.GetString("Domains_DefaultDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A domain must be enabled for Exchange in order for it to receive e-mail..
        /// </summary>
        internal static string Domains_Exchange {
            get {
                return ResourceManager.GetString("Domains_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is relayed to an e-mail server outside of this organization..
        /// </summary>
        internal static string Domains_ExternalRelay {
            get {
                return ResourceManager.GetString("Domains_ExternalRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is delivered to recipients in this organization or relayed to an e-mail server outside of this organization. Use this setting if the domain is shared by this Exchange organization and another messaging system..
        /// </summary>
        internal static string Domains_InternalRelay {
            get {
                return ResourceManager.GetString("Domains_InternalRelay", resourceCulture);
            }
        }
    }
}
