//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudPanel.localization.phrases", typeof(phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Company.
        /// </summary>
        internal static string Companies_CreateNew {
            get {
                return ResourceManager.GetString("Companies_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string Companies_DeleteConfirm1 {
            get {
                return ResourceManager.GetString("Companies_DeleteConfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete please type the name of the company (case sensitive).
        /// </summary>
        internal static string Companies_DeleteConfirm2 {
            get {
                return ResourceManager.GetString("Companies_DeleteConfirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Company.
        /// </summary>
        internal static string Companies_DeleteTitle {
            get {
                return ResourceManager.GetString("Companies_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a company to view.
        /// </summary>
        internal static string Companies_Title {
            get {
                return ResourceManager.GetString("Companies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Existing Company.
        /// </summary>
        internal static string Companies_UpdateExisting {
            get {
                return ResourceManager.GetString("Companies_UpdateExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview of your company.
        /// </summary>
        internal static string Company_OverviewDesc {
            get {
                return ResourceManager.GetString("Company_OverviewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string Delete_Confirm1 {
            get {
                return ResourceManager.GetString("Delete_Confirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the domain name you would like to add.
        /// </summary>
        internal static string Domains_Add {
            get {
                return ResourceManager.GetString("Domains_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect code. Please enter the code exactly as you see it..
        /// </summary>
        internal static string Email_CodeIncorrect {
            get {
                return ResourceManager.GetString("Email_CodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To disable email please type the following characters in the textbox below:.
        /// </summary>
        internal static string Email_DisableVerification {
            get {
                return ResourceManager.GetString("Email_DisableVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling email will delete all mailboxes, distribution groups, contacts, address lists, and everything else that relates to your company. This action is not reversable..
        /// </summary>
        internal static string Email_DisableWarning {
            get {
                return ResourceManager.GetString("Email_DisableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This company has not been enabled for Exchange server yet. Before this company can create mailboxes, distribution groups, contacts, and other Exchange objects, it must first be enabled..
        /// </summary>
        internal static string Email_EnableInfo {
            get {
                return ResourceManager.GetString("Email_EnableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string Error_ErrorUnknown {
            get {
                return ResourceManager.GetString("Error_ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well that wasn&apos;t supposed to happen! See below for the full error message:.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data from server.
        /// </summary>
        internal static string Load_FromServer {
            get {
                return ResourceManager.GetString("Load_FromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string Plans_DeleteConfirm1 {
            get {
                return ResourceManager.GetString("Plans_DeleteConfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Plan.
        /// </summary>
        internal static string Plans_DeleteTitle {
            get {
                return ResourceManager.GetString("Plans_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Reseller.
        /// </summary>
        internal static string Resellers_CreateNew {
            get {
                return ResourceManager.GetString("Resellers_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string Resellers_DeleteConfirm1 {
            get {
                return ResourceManager.GetString("Resellers_DeleteConfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete please type the name of the company (case sensitive).
        /// </summary>
        internal static string Resellers_DeleteConfirm2 {
            get {
                return ResourceManager.GetString("Resellers_DeleteConfirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete reseller because this reseller contains companies. Please remove the companies first..
        /// </summary>
        internal static string Resellers_DeleteContainsCompanies {
            get {
                return ResourceManager.GetString("Resellers_DeleteContainsCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name did not match. Please try again..
        /// </summary>
        internal static string Resellers_DeleteDidNotMatch {
            get {
                return ResourceManager.GetString("Resellers_DeleteDidNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Reseller.
        /// </summary>
        internal static string Resellers_DeleteTitle {
            get {
                return ResourceManager.GetString("Resellers_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a reseller to view their companies.
        /// </summary>
        internal static string Resellers_Title {
            get {
                return ResourceManager.GetString("Resellers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Existing Reseller.
        /// </summary>
        internal static string Resellers_UpdateExisting {
            get {
                return ResourceManager.GetString("Resellers_UpdateExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is required.
        /// </summary>
        internal static string Settings_ReqCompanyName {
            get {
                return ResourceManager.GetString("Settings_ReqCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting OU is required.
        /// </summary>
        internal static string Settings_ReqHostingOU {
            get {
                return ResourceManager.GetString("Settings_ReqHostingOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string Settings_ReqPassword {
            get {
                return ResourceManager.GetString("Settings_ReqPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Controller is required.
        /// </summary>
        internal static string Settings_ReqPrimaryDC {
            get {
                return ResourceManager.GetString("Settings_ReqPrimaryDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        internal static string Settings_ReqUsername {
            get {
                return ResourceManager.GetString("Settings_ReqUsername", resourceCulture);
            }
        }
    }
}
