//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPanel.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class words {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal words() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudPanel.localization.words", typeof(words).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Domain.
        /// </summary>
        internal static string AcceptedDomain {
            get {
                return ResourceManager.GetString("AcceptedDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activesync Plans.
        /// </summary>
        internal static string ActivesyncPlans {
            get {
                return ResourceManager.GetString("ActivesyncPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Domain.
        /// </summary>
        internal static string AddDomain {
            get {
                return ResourceManager.GetString("AddDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        internal static string Aliases {
            get {
                return ResourceManager.GetString("Aliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Login.
        /// </summary>
        internal static string AltLogin {
            get {
                return ResourceManager.GetString("AltLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving.
        /// </summary>
        internal static string Archiving {
            get {
                return ResourceManager.GetString("Archiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authoritative.
        /// </summary>
        internal static string Authoritative {
            get {
                return ResourceManager.GetString("Authoritative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string Billing {
            get {
                return ResourceManager.GetString("Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citrix.
        /// </summary>
        internal static string Citrix {
            get {
                return ResourceManager.GetString("Citrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citrix Plans.
        /// </summary>
        internal static string CitrixPlans {
            get {
                return ResourceManager.GetString("CitrixPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citrix Users.
        /// </summary>
        internal static string CitrixUsers {
            get {
                return ResourceManager.GetString("CitrixUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Plans.
        /// </summary>
        internal static string CompanyPlans {
            get {
                return ResourceManager.GetString("CompanyPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s Email.
        /// </summary>
        internal static string ContactsEmail {
            get {
                return ResourceManager.GetString("ContactsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s Name.
        /// </summary>
        internal static string ContactsName {
            get {
                return ResourceManager.GetString("ContactsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Email.
        /// </summary>
        internal static string DisableEmail {
            get {
                return ResourceManager.GetString("DisableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Groups.
        /// </summary>
        internal static string DistributionGroups {
            get {
                return ResourceManager.GetString("DistributionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name.
        /// </summary>
        internal static string DomainName {
            get {
                return ResourceManager.GetString("DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        internal static string Domains {
            get {
                return ResourceManager.GetString("Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown.
        /// </summary>
        internal static string Dropdown {
            get {
                return ResourceManager.GetString("Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Aliases.
        /// </summary>
        internal static string EmailAliases {
            get {
                return ResourceManager.GetString("EmailAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Status.
        /// </summary>
        internal static string EmailStatus {
            get {
                return ResourceManager.GetString("EmailStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable.
        /// </summary>
        internal static string EnableDisable {
            get {
                return ResourceManager.GetString("EnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        internal static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Relay.
        /// </summary>
        internal static string ExternalRelay {
            get {
                return ResourceManager.GetString("ExternalRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Access.
        /// </summary>
        internal static string FullAccess {
            get {
                return ResourceManager.GetString("FullAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Relay.
        /// </summary>
        internal static string InternalRelay {
            get {
                return ResourceManager.GetString("InternalRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Accepted Domain.
        /// </summary>
        internal static string IsAcceptedDomain {
            get {
                return ResourceManager.GetString("IsAcceptedDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        internal static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litigation Hold.
        /// </summary>
        internal static string LitigationHold {
            get {
                return ResourceManager.GetString("LitigationHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lync Users.
        /// </summary>
        internal static string LyncUsers {
            get {
                return ResourceManager.GetString("LyncUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox.
        /// </summary>
        internal static string Mailbox {
            get {
                return ResourceManager.GetString("Mailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailboxes.
        /// </summary>
        internal static string Mailboxes {
            get {
                return ResourceManager.GetString("Mailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox Plans.
        /// </summary>
        internal static string MailboxPlans {
            get {
                return ResourceManager.GetString("MailboxPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox Settings.
        /// </summary>
        internal static string MailboxSettings {
            get {
                return ResourceManager.GetString("MailboxSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Contacts.
        /// </summary>
        internal static string MaxContacts {
            get {
                return ResourceManager.GetString("MaxContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Domains.
        /// </summary>
        internal static string MaxDomains {
            get {
                return ResourceManager.GetString("MaxDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Groups.
        /// </summary>
        internal static string MaxGroups {
            get {
                return ResourceManager.GetString("MaxGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Mailboxes.
        /// </summary>
        internal static string MaxMailboxes {
            get {
                return ResourceManager.GetString("MaxMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Mail Public Folders.
        /// </summary>
        internal static string MaxMailPublicFolders {
            get {
                return ResourceManager.GetString("MaxMailPublicFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Resource Mailboxes.
        /// </summary>
        internal static string MaxResourceMailboxes {
            get {
                return ResourceManager.GetString("MaxResourceMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Users Allowed.
        /// </summary>
        internal static string MaxUsers {
            get {
                return ResourceManager.GetString("MaxUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Folders.
        /// </summary>
        internal static string PublicFolders {
            get {
                return ResourceManager.GetString("PublicFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resellers.
        /// </summary>
        internal static string Resellers {
            get {
                return ResourceManager.GetString("Resellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Mailboxes.
        /// </summary>
        internal static string ResourceMailboxes {
            get {
                return ResourceManager.GetString("ResourceMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send As.
        /// </summary>
        internal static string SendAs {
            get {
                return ResourceManager.GetString("SendAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send on Behalf.
        /// </summary>
        internal static string SendOnBehalf {
            get {
                return ResourceManager.GetString("SendOnBehalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to access your company.
        /// </summary>
        internal static string SignInMsg {
            get {
                return ResourceManager.GetString("SignInMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
